### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by Lili983** [Lili983/call-to-action-banner#1]
@MacKenzieRose
I don't know how to make the robot head the right size or position, the text the right position, and the button is in the wrong place.
Liliana

**Comment by MacKenzieRose** [comment]
Hey @Lili983!

So to start with, let's get your button to sit in the same place as the rest of your text content. The reason it's hiding at the bottom of your page is because in the index file, it's in a div tag all by itself, outside of your banner. Let's put it inside your div tag that has a class of "p" (line 20).

See if once that change is made if you still need help with your CSS styling.

MacKenzie

**Comment by MacKenzieRose** [comment]
If this issue has been resolved, feel free to close it :)

Cheers!
MacKenzie
